version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cert-auth-backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Optional: Set RSA keys via environment variables
      # - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
      # - RSA_PUBLIC_KEY=${RSA_PUBLIC_KEY}
    networks:
      - cert-auth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8081
    container_name: cert-auth-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cert-auth-network

networks:
  cert-auth-network:
    driver: bridge